cmake_minimum_required(VERSION 3.16)
project(galactus_db_cpp_driver VERSION 0.1.0 LANGUAGES CXX)
add_library(galactus_db_cpp_driver INTERFACE)
add_library(Galactus::Driver ALIAS galactus_db_cpp_driver)
target_compile_features(galactus_db_cpp_driver INTERFACE cxx_std_17)
target_include_directories(galactus_db_cpp_driver INTERFACE ${CMAKE_CURRENT_SOURCE_DIR}/include)
if(WIN32)
  target_link_libraries(galactus_db_cpp_driver INTERFACE ws2_32)
endif()
option(GALACTUS_BUILD_TESTS "Build driver tests" OFF)
if(GALACTUS_BUILD_TESTS)
  enable_testing()
  add_executable(galactus_test tests/test.cpp)
  target_link_libraries(galactus_test PRIVATE Galactus::Driver)
  add_test(NAME galactus_test COMMAND galactus_test)
  set_tests_properties(galactus_test PROPERTIES WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}")
endif()
